### ISSUE TITLE
xray 状态: 未运行

### ISSUE THREAD

**Issue by NoRRt** [qist/xray-ui#1]
xray-ui面板状态: 已运行
是否开机自启: 是
**xray 状态: 未运行..**

**Comment by qist** [comment]
手动部署的话你的service WorkingDirectory=/usr/local/xray-ui/ 一定要写正确，你也可以看看服务日志，应该有报错信息。

**Comment by NoRRt** [comment]
bin
xray-ui
xray-ui.service
xray-ui.sh

**Comment by qist** [comment]
./xray-ui 运行看看报错什么。bin目录有没文件，没有你web也没下载3个文件一个二进制，两个ip文件。

**Comment by NoRRt** [comment]
problem solved
