### ISSUE TITLE
vmess 和 trojan协议的CipherSuites 如果设置为auto 会导致xray 无法启动

### ISSUE THREAD

**Issue by fireinrain** [qist/xray-ui#111]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

你好作者大大，我在使用这个项目的时候发现 如果节点设置为vmess 或者trojan  CipherSuites 选择auto，
会导致xray无法启动
如图所示：
<img width="456" alt="image" src="https://github.com/qist/xray-ui/assets/14249262/3b67ddd4-bad5-4277-a504-1149e1bd9efd">
<img width="307" alt="image" src="https://github.com/qist/xray-ui/assets/14249262/570368ad-bd9e-4659-aef4-86f464ead3ff">

以下是config.json片段：
<img width="463" alt="image" src="https://github.com/qist/xray-ui/assets/14249262/e21f3282-ad57-409d-b487-b5c1951e6e56">

这里的空string 就是导致配置无法序列化到go 结构体，我尝试删除auto 选择一个加密方式，xray能起来
希望大大修复一下 万分感谢

### Version of xray-ui

<details>

```console
# Paste here
```
最新版本
</details>

### xray-ui log reports or xray log

<details>

```console
# paste log here
```
如上图
</details>

**Comment by qist** [comment]
已经收到这个 这个是在清理流量会出现这个问题。你可以重新选择一次应该就可以了。

**Comment by fireinrain** [comment]
确实 ×掉重新选 保存之后就没问题
