### ISSUE TITLE
希望UP大大    加一个API请求接口相关的功能

### ISSUE THREAD

**Issue by Huangqiankun** [qist/xray-ui#120]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

比如说，什么增删改查入站、增删改查客户端相关等等。这些都可以用外部请求接口来实现

### Version of xray-ui

# Paste here

### xray-ui log reports or xray log

# Paste here

**Comment by qist** [comment]
你可以看看`https://github.com/MHSanaei/3x-ui` 这个好像有
