### ISSUE TITLE
xary 状态一直error

### ISSUE THREAD

**Issue by lleeopen** [qist/xray-ui#171]
从装好面板进入就显示error，不管切换哪个版本都是error，用ygkkk的那个就正常没问题

![2024-6-22 22-4-51](https://github.com/qist/xray-ui/assets/35162785/43f6e397-736e-403f-9591-014dfec311b6)

![image](https://github.com/qist/xray-ui/assets/35162785/0c5f52c1-87cd-442f-81f5-67eaa482a9e4)

**Comment by qist** [comment]
鼠标指到error 上面显示什么应该是配置有不兼容的地方。

**Comment by qist** [comment]
旧的是不是很久以前配置过tls  的CipherSuites  如果配置了你重新选择一次应该就可以了。

**Comment by lleeopen** [comment]
> 旧的是不是很久以前配置过tls 的CipherSuites 如果配置了你重新选择一次应该就可以了。

vps重装系统后，然后全新装的你的x-ui，不存在以前配置过，登陆进去xary就是error，后来换ygkkk维护的x-ui就是正常使用的没问题

**Comment by lleeopen** [comment]
我今天又试了一下，全新安装登陆进去就是error

![image](https://github.com/qist/xray-ui/assets/35162785/b0adc34a-85f8-4d53-bf8b-389335644d52)

![image](https://github.com/qist/xray-ui/assets/35162785/5725ceb2-60e0-40f5-949e-4a02525424bc)

**Comment by qist** [comment]
你是arm 版的，你切换xray 版本看看， /etc/xray-ui 里面有数据的然后你看看 bin/config.json 这个直接 二进制启动看看可以不。

**Comment by lleeopen** [comment]
抱歉你的脚本我可能用不了或者是我不会用，请关了此问题吧，不过还是谢谢你的回答

**Comment by qist** [comment]
你是arm7 的这边我只是编译的arm8的
