### ISSUE TITLE
服务器有ipv6，如何在保留ipv4节点的情况下使用ipv6搭建节点

### ISSUE THREAD

**Issue by facebook20146** [qist/xray-ui#172]
目前用大佬的脚本搭建的xui，如何服务器有ipv6，如何在保留ipv4节点的情况下使用ipv6搭建节点
希望大佬给指导一下，本人只会一件脚本，希望大佬能弄得简单点

**Comment by qist** [comment]
默认支持v4 v6 你解析到v6 ip 就可以用了啊。

**Comment by qist** [comment]
监听 IP 改成v6 的 set sockopt 里面可用选择网卡 跟V6Only

**Comment by qist** [comment]
https://xtls.github.io/config/transport.html#sockoptobject
V6Only: true | false

填写 true 时，监听 :: 地址仅接受 IPv6 连接。仅支持 Linux。

**Comment by facebook20146** [comment]
> 监听 IP 改成v6 的 set sockopt 里面可用选择网卡 跟V6Only

是在xui里面改还是服务器里面

**Comment by qist** [comment]
xui 
![image](https://github.com/qist/xray-ui/assets/7844620/007359fb-5135-4b06-854a-684457332f95)

**Comment by qist** [comment]
config.json 手动修改没效了的。别手动修改。

**Comment by facebook20146** [comment]
> xui ![image](https://private-user-images.githubusercontent.com/7844620/343629463-007359fb-5135-4b06-854a-684457332f95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjIzMzQsIm5iZiI6MTcxOTQ2MjAzNCwicGF0aCI6Ii83ODQ0NjIwLzM0MzYyOTQ2My0wMDczNTlmYi01MTM1LTRiMDYtODU0YS02ODQ0NTczMzJmOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjdUMDQyMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2E3NmQ2OTczNzA4OGVlYmRmZGEyZmUzNzE3NmM5OTg4ZTE1ZGFmMWYzYTlkNTQxOTI4MmVlMjdiM2VlMjJjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JgP2hjj5i18UXcG2FJUOqAIep6YzNkQ2mc5NlpJ1SzE)

谢谢大佬，还有一个问题，也就是我的节点地址从ipv4换成IPv6，其他不变的情况下，是不是可以照常使用

**Comment by qist** [comment]
那个打开只能v6 连接了v4 就不能用了哟。不开启v4 v6 都能用的。

**Comment by facebook20146** [comment]
> 是的可以直接使用的就换个地址，那个打开只能v6 连接了v4 就不能用了哟。不开启v4 v6 都能用的。

是不是可以控制单个节点只使用ipv6，其他节点v4+v6

**Comment by qist** [comment]
V6Only 就是控制单个接单v6
