### ISSUE TITLE
可否调整下传输选项的css

### ISSUE THREAD

**Issue by tqangxl** [qist/xray-ui#184]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

可否调整下默认传输选项的(TCP)css
![image](https://github.com/user-attachments/assets/44e19624-a176-41d6-ae38-6c47101752aa)

![image](https://github.com/user-attachments/assets/0354c1f9-d85d-4629-91d9-44865cd2f7e7)

**Comment by qist** [comment]
修改了。
