### ISSUE TITLE
请求集成自动申请ssl功能

### ISSUE THREAD

**Issue by kireiyume** [qist/xray-ui#194]
你好：
        我作为一个用户，觉得此软件十分不错，美中不足就是好像您的意图是只用reality方式，可是想请求您集成ssl证书功能，能够通过定时任务来执行更新证书，采用cloudfare的api方式就好

**Comment by qist** [comment]
你可以测试一下

**Comment by kireiyume** [comment]
> 你可以测试一下
> 
> ```
> xray-ui  update_shell
> 更新 或者使用下面方案下载更新
>     wget --no-check-certificate -O /usr/bin/xray-ui https://raw.githubusercontent.com/qist/xray-ui/main/xray-ui.sh
>     chmod +x /usr/bin/xray-ui
> xray-ui 选择申请证书地方
> ```
> 
> 看看能正常申请证书么

好的，谢谢
