### ISSUE TITLE
是否考虑添加h2 reality 协议的方式

### ISSUE THREAD

**Issue by yzx1208** [qist/xray-ui#20]
是否考虑添加h2 reality 协议的方式

**Comment by qist** [comment]
你选择http 就可以了，客户端选择h2

**Comment by qist** [comment]
https://github.com/qist/xray-ui/blob/main/media/vless%2BH2%2Breality.png

**Comment by yzx1208** [comment]
感谢作者大大的指导，我先按照您的操作试试看。
