### ISSUE TITLE
大佬，更新后，我按照命令安装证书，提示安装失败，再次尝试，提示已经申请过，现在需要大佬帮忙

### ISSUE THREAD

**Issue by facebook20146** [qist/xray-ui#206]
如题，大佬麻烦回复下，最下面没截图上，就是提示没成功，现在也进不去面板
![Uploading Screenshot_2024-11-03-18-12-15-38_61c78dc80ee02b53007c815fefe993e3.jpg…]()

**Comment by qist** [comment]
你没用cf dns 去申请证书把。
你的域名用那个dns 管理的。

**Comment by facebook20146** [comment]
> 你没用cf dns 去申请证书把。 你的域名用那个dns 管理的。

您的意思是我的这个域名是自带dns解析，所以没成功，现在该怎么解决，请说详细点

**Comment by qist** [comment]
建议ng上面配置证书。
xray-ui ssl_main 
选择1去前面确保 如果80端口被占用记得修改成别的端口
或者手动签发用下面的命令
curl https://get.acme.sh | sh
acme.sh --upgrade --auto-upgrade # 开启自动升级
记得改成自己的域名
acme.sh --issue --nginx -d qist.cc -d www.qist.cc  -m xxxx@gmail.com --force  -k 8192

mkdir -p /root/qist.cc/

acme.sh --install-cert -d qist.cc  \
--key-file /root/qist.cc/private.key \
--ca-file /root/qist.cc/ca.crt \
--cert-file /root/qist.cc/cert.crt \
--fullchain-file /root/qist.cc/fullchain.crt

**Comment by facebook20146** [comment]
> 建议ng上面配置证书。 xray-ui ssl_main 选择1去前面确保 如果80端口被占用记得修改成别的端口 或者手动签发用下面的命令 curl https://get.acme.sh | sh acme.sh --upgrade --auto-upgrade # 开启自动升级 记得改成自己的域名 acme.sh --issue --nginx -d qist.cc -d [www.qist.cc](http://www.qist.cc) -m [xxxx@gmail.com](mailto:xxxx@gmail.com) --force -k 8192
> 
> mkdir -p /root/qist.cc/
> 
> acme.sh --install-cert -d qist.cc --key-file /root/qist.cc/private.key --ca-file /root/qist.cc/ca.crt --cert-file /root/qist.cc/cert.crt --fullchain-file /root/qist.cc/fullchain.crt

是不是用这个也行，我那会查的，不敢用

安装 Acme

curl https://get.acme.sh | sh
申请证书

~/.acme.sh/acme.sh --register-account -m 你的邮箱 
~/.acme.sh/acme.sh --issue -d 你的域名 --standalone
改证书存放位置

~/.acme.sh/acme.sh --installcert -d 你的域名 --key-file /root/private.key --fullchain-file /root/cert.crt
域名申请时间超时的运行这个命令然后再申请

~/.acme.sh/acme.sh --set-default-ca --server letsencrypt
证书位置是 /root/cert.crt

密钥位置是 /root/private.key

**Comment by qist** [comment]
~/.acme.sh/acme.sh --set-default-ca --server letsencrypt 这个应该先执行 然后~/.acme.sh/acme.sh --register-account -m 你的邮箱 这样 是可以的

**Comment by facebook20146** [comment]
> 建议ng上面配置证书。 xray-ui ssl_main 选择1去前面确保 如果80端口被占用记得修改成别的端口 或者手动签发用下面的命令 curl https://get.acme.sh | sh acme.sh --upgrade --auto-upgrade # 开启自动升级 记得改成自己的域名 acme.sh --issue --nginx -d qist.cc -d [www.qist.cc](http://www.qist.cc) -m [xxxx@gmail.com](mailto:xxxx@gmail.com) --force -k 8192
> 
> mkdir -p /root/qist.cc/
> 
> acme.sh --install-cert -d qist.cc --key-file /root/qist.cc/private.key --ca-file /root/qist.cc/ca.crt --cert-file /root/qist.cc/cert.crt --fullchain-file /root/qist.cc/fullchain.crt

大佬，我不会用nigix，我用你的命令，他提示未知的参数，我自己用我回复你下面的命令，安装证书成功，但是还是无法打开面板，提示net::ERR_CONNECTION_CLOSED

现在该怎么办，或者有没有可能更新面板，给几次IP登录机会，把面板路径填上去，是不是才行

**Comment by facebook20146** [comment]
> > 建议ng上面配置证书。 xray-ui ssl_main 选择1去前面确保 如果80端口被占用记得修改成别的端口 或者手动签发用下面的命令 curl https://get.acme.sh | sh acme.sh --upgrade --auto-upgrade # 开启自动升级 记得改成自己的域名 acme.sh --issue --nginx -d qist.cc -d [www.qist.cc](http://www.qist.cc) -m [xxxx@gmail.com](mailto:xxxx@gmail.com) --force -k 8192
> > mkdir -p /root/qist.cc/
> > acme.sh --install-cert -d qist.cc --key-file /root/qist.cc/private.key --ca-file /root/qist.cc/ca.crt --cert-file /root/qist.cc/cert.crt --fullchain-file /root/qist.cc/fullchain.crt
> 
> 大佬，我不会用nigix，我用你的命令，他提示未知的参数，我自己用我回复你下面的命令，安装证书成功，但是还是无法打开面板，提示net::ERR_CONNECTION_CLOSED
> 
> 现在该怎么办，或者有没有可能更新面板，给几次IP登录机会，把面板路径填上去，是不是才行

我用大佬的脚本，按照我自定义重新设置了路径，然后就可以了

**Comment by facebook20146** [comment]
> ~/.acme.sh/acme.sh --set-default-ca --server letsencrypt 这个应该先执行 然后~/.acme.sh/acme.sh --register-account -m 你的邮箱 这样 是可以的

大佬，晚上终于配置好了证书，怎么自动更新，我看还得用nigix，我查了下还挺复杂，大佬有没有简单的方法

**Comment by qist** [comment]
``` 
acme.sh --upgrade --auto-upgrade  这个就好自带签发证书了。证书会自动更新。
acme.sh --install-cert -d qist.cc  --ecc \
 --ecc --key-file /root/qist.cc/ecc/private.key \
 --ca-file /root/qist.cc/ecc/ca.crt \
 --cert-file /root/qist.cc/ecc/cert.crt \
 --fullchain-file /root/qist.cc/ecc/fullchain.crt \
 --reloadcmd "systemctl restart xray-ui;systemctl restart nginx"
```

**Comment by facebook20146** [comment]
> ```
> acme.sh --upgrade --auto-upgrade  这个就好自带签发证书了。证书会自动更新。
> 下面就是更新好证书重启业务命令
> acme.sh --install-cert -d qist.cc   \
>  --ecc --key-file /root/qist.cc/ecc/private.key \
>  --ca-file /root/qist.cc/ecc/ca.crt \
>  --cert-file /root/qist.cc/ecc/cert.crt \
>  --fullchain-file /root/qist.cc/ecc/fullchain.crt \
>  --reloadcmd "systemctl restart xray-ui;systemctl restart nginx"
> ```

大佬，我是用的下面的命令弄得，然后证书位置也是在这个下面命令位置，如果更新，怎么换命令，求教谢谢


安装 Acme

curl https://get.acme.sh/ | sh
申请证书

~/.acme.sh/acme.sh --register-account -m 你的邮箱
~/.acme.sh/acme.sh --issue -d 你的域名 --standalone
改证书存放位置

~/.acme.sh/acme.sh --installcert -d 你的域名 --key-file /root/private.key --fullchain-file /root/cert.crt
域名申请时间超时的运行这个命令然后再申请

~/.acme.sh/acme.sh --set-default-ca --server letsencrypt
证书位置是 /root/cert.crt

密钥位置是 /root/private.key

**Comment by qist** [comment]
重新执行正确的命令就更新了。crontab -l 看定时任务 
```
cd /root/.acme.sh/qist.cc 改成你的域名
 cat qist.cc.conf 你的域名相关配置文件
Le_ReloadCmd=' ' 内容就是更新证书执行命令，BASE64 加密
__ACME_BASE64__START_加密的内容可以解密__ACME_BASE64__END_
echo "加密内容解密 "| base64 -d 可以替换这个内容  删除-d 就是加密
```
