### ISSUE TITLE
cer installation failed 

### ISSUE THREAD

**Issue by lotus6808** [qist/xray-ui#208]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

AM EST 2024] The domain 'xxx.xx' seems to already have an ECC cert, let's use it.
[Mon Nov  4 10:17:21 AM EST 2024] Installing cert to: /root/cert/xxx.xx.cer
[Mon Nov  4 10:17:21 AM EST 2024] Installing CA to: /root/cert/ca.cer
/usr/bin/xray-ui: line 724: --key-file: command not found

### Version of xray-ui

24.10.11

### xray-ui log reports or xray log

I want to access webui by https

**Comment by ZizhenWang** [comment]
hi, how do you fix this error

**Comment by qist** [comment]
xray-ui  输入 16 更新最新脚本应该就可以了。

**Comment by ZizhenWang** [comment]
> xray-ui 输入 16 更新最新脚本应该就可以了。

大佬好，我现在的版本是24.11.15
第一次安装证书失败后，我输入19选择1，获取SSL，会提示
> [ERR] 系统中已存在该域名的证书，不能重复签发，当前证书详情:

然后输入19选择2，撤销证书，提示
> [INF] 证书已撤销

这之后再选择1，还是会提示已存在该域名证书
并且在这个过程中xray-ui一直显示的是
> 证书 is not set
> CA is not set

请教下要如何处理呀

**Comment by ZizhenWang** [comment]
另外，我现在是在centos 7 x86_64 上进行部署的，大佬是在什么系统上跑的，我可以切换一下系统 @qist

**Comment by qist** [comment]
很抱歉一开始那个代码有点问题，
```
domain 你的域名 看看 里面有没文件 
你ls  /root/cert/$(domain) 
看看有没问题 没有你手动执行一下下面的命令
domain 记得改成你的域名
    ~/.acme.sh/acme.sh --installcert -d ${domain} \
        --ca-file /root/cert/ca.cer \
        --cert-file /root/cert/${domain}.cer \
        --key-file /root/cert/${domain}/privkey.pem \
        --fullchain-file /root/cert/${domain}/fullchain.pem
然后执行 xray-ui  然后输入22 跟xray-ui 配置证书
```

**Comment by ZizhenWang** [comment]
> ls /root/cert/${domin} 

这个文件夹下面是空的
执行acme.sh的时候会报错 
> cat: /root/.acme.sh/${domain}_ecc/${domain}.cer: 没有那个文件或目录

不知道是不是环境或者系统啥的有问题

**Comment by qist** [comment]
${domin} 你要改成你的域名啊！或者
```
cd ~/.acme.sh/
删除你的域名
rm -r tycng.com 改成自己的域名啊
然后重写签发。
```

**Comment by ZizhenWang** [comment]
嗯嗯，我输入命令的时候已经把domain改成我的域名了， 只是写issue的时候改回来方便理解
重新签发是指再运行上面给的acme.sh命令吗，还是用xray-ui 19进行呀

**Comment by qist** [comment]
你删除了就19去签发。记得更新16. 更新 xray-ui 脚本 这个一开始安装文件哪里有问题。

**Comment by ZizhenWang** [comment]
多谢大佬，这次成功了

**Comment by ZizhenWang** [comment]
碰到了新问题

我在xray-ui选择19和20设置了ssl和cloudflare ssl之后，通过TLS配置
> /usr/local/xray-ui/xray-ui cert -webCert /root/cert/你的域名/fullchain.pem -webCertKey /root/cert/你的域名/privkey.pem
> xray-ui restart

运行失败，提示
> 面板启动失败，可能是因为启动时间超过了两秒，请稍后查看日志信息

此时xray-ui面板的状态显示
> 证书文件: /root/cert/${domain}/fullchain.pem
私钥文件: /root/cert/${domain}/privkey.pem
CA is not set

查看日志信息后发现有个报错是
> 2024/11/17 21:34:02 open /root/cert/${domain}/fullchain.pem: no such file or directory

看起来是这个文件找不到，想问下是重启失败的原因吗，要怎么解决呀

**Comment by qist** [comment]
那个目录有对应的文件没有。没有怎么签发成功的。看看文件名字是不是有问题。 重置不给文件路径就删除证书了就能正常启动。

**Comment by qist** [comment]
cf 签发文件 名字有变我看代码
```
        ~/.acme.sh/acme.sh --installcert -d ${CF_Domain} -d *.${CF_Domain} --ca-file /root/cert/ca.cer \
            --cert-file /root/cert/${CF_Domain}.cer --key-file /root/cert/${CF_Domain}.key \
            --fullchain-file /root/cert/fullchain.cer
```

**Comment by ZizhenWang** [comment]
好的我跑一下，这里的cf domain就是cf global key吗

**Comment by qist** [comment]
19单证书签发 用本地的端口签发的 20 是泛域名签发 cf建议配置一个低权限签发 cf api 权限 
权限 
区域 DNS 编辑
区域 区域 读取

区域资源
包括 所有区域
其它默认

**Comment by ZizhenWang** [comment]
还是有点问题，辛苦大佬再看下

执行完19之后，结果显示是正常的
> [INF] 证书安装成功，开启自动续期...
[2024年 11月 17日 星期日 21:53:10 EST] Already up to date!
[2024年 11月 17日 星期日 21:53:10 EST] Upgrade successful!
[INF] 自动续期成功，证书详情如下:
-rw-r--r-- 1 root root 1.6K 11月 17 21:53 cert/ca.cer
-rw-r--r-- 1 root root 2.8K 11月 17 21:31 cert/fullchain.cer
-rw-r--r-- 1 root root 1.3K 11月 17 21:53 cert/${domain}.cer
-rw------- 1 root root  227 11月 17 21:31 cert/${domain}.key

然后使用大佬提供的这段代码运行
> cf 签发文件 名字有变我看代码
> 
> ```
>         ~/.acme.sh/acme.sh --installcert -d ${CF_Domain} -d *.${CF_Domain} --ca-file /root/cert/ca.cer \
>             --cert-file /root/cert/${CF_Domain}.cer --key-file /root/cert/${CF_Domain}.key \
>             --fullchain-file /root/cert/fullchain.cer
> ```

结果也是正常的，xray-ui restart之后 **证书文件，私钥文件，CA mTLS** 都可以正常显示，但是通过https://你的域名:12212/xrayui 长时间无响应

然后我试了下xray-ui 20，就又无法启动了，还是之前路径找不到的问题

想问下https访问域名失败，这个可能是什么原因，我要从哪里试着修复啊

**Comment by qist** [comment]
设置路径是多少，/root/cert/fullchain.cer 证书 /root/cert/${CF_Domain}.key 密钥 就是  mtls 要配置客户端证书的建议别设置 也就是别设置ca MTLS 是双向验证的。

**Comment by qist** [comment]
请输入选择 [0-23]: 22

确定要重新设置证书吗 [默认n]: y
[DEG] 请输入证书路径:
输入您的证书路径:/apps/nginx/sslkey/ecc/fullchain.crt
[DEG] 证书路径为:/apps/nginx/sslkey/ecc/fullchain.crt
[DEG] 请输入密钥路径:
输入您的密钥路径:/apps/nginx/sslkey/ecc/private.key
[DEG] 您的密钥是:/apps/nginx/sslkey/ecc/private.key
set certificate public key success
set certificate private key success
set mTLS ca success

是否重启面板，重启面板也会重启 xray [默认y]: y
xray-ui 与 xray 重启成功

当前面板信息设置如下:
登录用户名: 
登录密码: 
登录端口: 
Web 路径: 
证书文件: /apps/nginx/sslkey/ecc/fullchain.crt
私钥文件: /apps/nginx/sslkey/ecc/private.key
CA is not set
------------------------------------------
已安装最新版本：24.11.15 ，如有更新，此处会自动提示

**Comment by qist** [comment]
还有你证书签发好了就被反复的去签发了。lst 有请求限制的。19 20 选择一个就可以了别两个都运行。

**Comment by qist** [comment]
登录端口 防火墙一定要放行啊。

**Comment by ZizhenWang** [comment]
哦哦好的，我现在的情况是

1. 运行19
端口设置的80
> [INF] 自动续期成功，证书详情如下:
-rw-r--r-- 1 root root 1.6K 11月 17 21:53 cert/ca.cer
-rw-r--r-- 1 root root 2.8K 11月 17 21:31 cert/fullchain.cer
-rw-r--r-- 1 root root 1.3K 11月 17 21:53 cert/${domain}.cer
-rw------- 1 root root  227 11月 17 21:31 cert/${domain}.key

这时
> ls /root/cert
ca.cer  ${domain}  ${domain}.cer
ls ~/.acme.sh/
${domain}_ecc xxx(其他文件)

3. 配置tls
> /usr/local/xray-ui/xray-ui cert -webCert /root/cert/你的域名/fullchain.pem -webCertKey /root/cert/你的域名/privkey.pem
xray-ui

此时xray-ui显示
> Web 路径: /xrayui/
证书文件: /root/cert/${domain}/fullchain.pem
私钥文件: /root/cert/${domain}/privkey.pem
CA is not set

4. 防火墙设置
> firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0 eth1
  sources:
  services: dhcpv6-client http https ssh
  ports: 80/tcp 12212/tcp 12212/udp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

6. 访问 https://www.${domain}:12212/xrayui 显示访问时间过长

**Comment by qist** [comment]
手动配置证书要重启xray-ui restart 才可以。

**Comment by qist** [comment]
19 的话文件名字不一样。
```
    ~/.acme.sh/acme.sh --installcert -d ${domain} \
        --ca-file /root/cert/ca.cer \
        --cert-file /root/cert/${domain}.cer \
        --key-file /root/cert/${domain}/privkey.pem \
        --fullchain-file /root/cert/${domain}/fullchain.pem
```

**Comment by qist** [comment]
你cf 那边cdn 别开启 那朵云。

**Comment by ZizhenWang** [comment]
感谢大佬回复，我配置完证书之后restart过了，我看了下acem命令这三个文件都是确实存在的
> --cert-file /root/cert/${domain}.cer
--key-file /root/cert/${domain}/privkey.pem
--fullchain-file /root/cert/${domain}/fullchain.pem

对比了下xray面板中显示的路径也是一致的
> 证书文件: /root/cert/${domain}/fullchain.pem
私钥文件: /root/cert/${domain}/privkey.pem
CA is not set

我F12看了下请求网站的时候，就只有xrayui一个请求然后一直没有响应
![image](https://github.com/user-attachments/assets/b3036409-bb69-4d11-9664-11ea30a7f844)


另外还想请教下cf cdn在哪里找哇， 我第一次用不太熟练

**Comment by qist** [comment]
![image](https://github.com/user-attachments/assets/45f13e25-7bdd-49b3-8e3f-bdf7939d18a6)
你要关闭才可以访问非80 443端口

**Comment by lotus6808** [comment]
> hi, how do you fix this error
No I didn't.At first I thought it was the system issues,so I reinstalled it, I tried latest Debian and Ubuntu but this problem remains, after several hours, it seemed hopeless so I gave up this script, instead run with other developer's script, problem solved.

**Comment by ZizhenWang** [comment]
可以了，多谢老哥

**Comment by ZizhenWang** [comment]
> > hi, how do you fix this error
> > No I didn't.At first I thought it was the system issues,so I reinstalled it, I tried latest Debian and Ubuntu but this problem remains, after several hours, it seemed hopeless so I gave up this script, instead run with other developer's script, problem solved.

got it, if you still want to use this script, you can follow the discussion before and it works for me, but I think you need to translate it to your language :-)
