### ISSUE TITLE
面板中“默认cn IP网址为blocked”，对配置防dns泄露有影响吗

### ISSUE THREAD

**Issue by facebook20146** [qist/xray-ui#209]
我想要路由器中openclash配置防dns泄露的配置，咱们面板中的这句话是啥意思，对配置有影响吗？

“默认CN IP 网址 为 blocked、修改请到《面板配置》下面的《xray 相关设置》进行配置”

**Comment by qist** [comment]
这个意思就是cn的ip都是拦截的不能访问的。不影响。一般不建议开启不然探测到就封你服务器ip。所以我默认blocked了。

**Comment by facebook20146** [comment]
> 这个意思就是cn的ip都是拦截的不能访问的。不影响。一般不建议开启不然探测到就封你服务器ip。所以我默认blocked了。

谢谢大佬
