### ISSUE TITLE
面板重启失败，可能是因为启动时间超过了两秒，请稍后查看日志信息

### ISSUE THREAD

**Issue by PunkFleet** [qist/xray-ui#215]
日志：
```
Nov 22 09:00:02 eu systemd[1]: Started xray-ui.service - xray-ui Service.
Nov 22 09:00:02 eu xray-ui[11717]: 2024/11/22 09:00:02 xray-ui 24.11.22
Nov 22 09:00:02 eu xray-ui[11717]: 2024/11/22 09:00:02 open /root/cert/eu.test.com.cer: no such file or directory
Nov 22 09:00:02 eu systemd[1]: xray-ui.service: Deactivated successfully.
```

但我通过一件脚本进行的安装，而且也已经安装了证书，但是这个提示真的搞不懂是怎么做的
```
不使用ssh 转发请配置nginx https代理或者xray-ui 配置证书
下面是xray-ui tls mTLS 配置信息
证书管理 xray-ui ssl_main  cf 证书申请 xray-ui ssl_CF
TLS 配置 /usr/local/xray-ui/xray-ui cert -webCert /root/cert/你的域名/fullchain.pem -webCertKey /root/cert/你的域名/privkey.pem 重启 xray-ui restart 生效
mTLS 配置 /usr/local/xray-ui/xray-ui cert -webCert /root/cert/你的域名/fullchain.pem -webCertKey /root/cert/你的域名/privkey.pem -webCa /root/cert/ca.cer 重启 xray-ui restart 生效
访问：https://你的域名:5191/dashboard
mTLS windows 使用.....
生成windows客户端证书 client.p12...
openssl pkcs12 -export -out client.p12 -inkey /root/cert/你的域名/privkey.pem -in  /root/cert/.cer -certfile /root/cert/ca.cer
client.p12: windows客户端证书 记得设置密码 导入证书需要密码
client.p12 文件导入windows系统 桌面双击打开->导入->下一步->将所有证书都放入下列存储->个人->完成 如果导入失败开始菜单搜证书 打开管理用户证书管理->个人->所有任务->导入->输入密码


```

**Comment by qist** [comment]
你要确认  /root/cert/eu.test.com.cer 文件是存在的 ls  /root/cert/*

**Comment by PunkFleet** [comment]
我安装后使用 `xray-ui ssl_main cf` ，但是`ls /root/cert/*`却No such file or directory
请问如何查看ssl默认的安装路径，似乎教程里没有指明这一点，导致在初次安装后无法正常启动

**Comment by qist** [comment]
xray-ui ssl_main  xray-ui ssl_CF 二选一 别两个都执行，第一个你要确保80 端口没被占用防火墙需要放行。第二个就是cf dns 模式申请证书。

**Comment by PunkFleet** [comment]
> xray-ui ssl_main xray-ui ssl_CF 二选一 别两个都执行，第一个你要确保80 端口没被占用防火墙需要放行。第二个就是cf dns 模式申请证书。

<img width="886" alt="image" src="https://github.com/user-attachments/assets/8c7af69c-e498-4184-a145-0c70e627990d">

似乎没办法正确卸载和安装证书

**Comment by PunkFleet** [comment]
<img width="880" alt="Screenshot 2024-11-23 at 11 17 25" src="https://github.com/user-attachments/assets/4702b1d3-f85e-4a0d-8edc-85aad020b3ef">
<img width="523" alt="Screenshot 2024-11-23 at 11 17 30" src="https://github.com/user-attachments/assets/c46bba0b-32ad-48fc-b730-2d5feb23ec3c">
现在访问https://域名:19814/dashboard/  得到错误Web server is down Error code 521

**Comment by qist** [comment]
非 443 端口 cf 记得关闭加速。

**Comment by qist** [comment]
看看 这个 https://github.com/qist/xray-ui/issues/208
