### ISSUE TITLE
小白建议添加更多内网IP允许访问http页面

### ISSUE THREAD

**Issue by cola77777** [qist/xray-ui#218]
比如192.168.*还有172.17.*或者172.18.*等等
我喜欢用docker搭建服务，docker的nginx会通过172.17.*之类的ip访问http页面，在nginx反向代理实现https访问面板
使用这些内网段IP访问不暴露公网也是安全的
虽然也可以使用命令行配置证书，但是略麻烦

**Comment by qist** [comment]
晚点我修改一下。

**Comment by qist** [comment]
已经添加了

**Comment by cola77777** [comment]
> 你好，我也使用docker，为什么无法获取到内网的IP？是需要配置什么参数吗？ ![image](https://private-user-images.githubusercontent.com/19897322/394221535-260a1c08-f7d6-4dfa-b93d-15a95d6207d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjgzMTcsIm5iZiI6MTczMzgyODAxNywicGF0aCI6Ii8xOTg5NzMyMi8zOTQyMjE1MzUtMjYwYTFjMDgtZjdkNi00ZGZhLWI5M2QtMTVhOTVkNjIwN2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEwNTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjgyYjE2OWFlYTUwOGNlMGIwM2VlMDQ0MjBlYjI1MjAwNTM2ZWQ5ZGI4NDQ1YzllYzIzZWRhNDA4MDRmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zw2wncWr3l0qeKvVdHo6uoZ6r3KYJw7wXbXtEjdl5g4) ![image](https://private-user-images.githubusercontent.com/19897322/394221648-6e32ecce-3d66-41c2-b833-cbf297a84de8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjgzMTcsIm5iZiI6MTczMzgyODAxNywicGF0aCI6Ii8xOTg5NzMyMi8zOTQyMjE2NDgtNmUzMmVjY2UtM2Q2Ni00MWMyLWI4MzMtY2JmMjk3YTg0ZGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDEwNTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZDZkMTg3ZjFhNjU4YzQxNDZiMDQxODA2ZmYxNTkwMGQ2YjYyYzJiMGNkNjhmODFiZmU0YWI2MmQ0MTcwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7kqM6QjC5vY8KqpJERaO-Sv8qztSc8_XrJNn5Rlybv4)

先用docker network create --subnet=172.18.0.0/16 mynet   创建一个名为mynet新的网络
这是我的docker compose文件，你根据你的需要改一下
---
services:
  xui:
    image: juestnow/xray-ui:latest
    container_name: xui
    ports:
      - 443:443
    expose:
      - 54321
    volumes:
      - ./db:/etc/xray-ui
      - ./cert:/root/cert
    networks:
      mynet:
        ipv4_address: 172.18.0.51
    restart: unless-stopped

networks:
  mynet:
    name: mynet
    external: true
最后docker exec -ti xui /app/xray-ui setting -listen 172.18.0.51   设置监听固定ip

**Comment by cola77777** [comment]
@maolei133
先用docker network create --subnet=172.18.0.0/16 mynet 创建一个名为mynet新的网络
这是我的docker compose文件，你根据你的需要改一下
---
services:
  xui:
    image: juestnow/xray-ui:latest
    container_name: xui
    ports:
      - 443:443
    expose:
      - 54321
    volumes:
      - ./db:/etc/xray-ui
      - ./cert:/root/cert
    networks:
      mynet:
        ipv4_address: 172.18.0.51
    restart: unless-stopped

networks:
  mynet:
    name: mynet
    external: true
最后docker exec -ti xui /app/xray-ui setting -listen 172.18.0.51 设置监听固定ip
