### ISSUE TITLE
关于ssl申请后自动应用的建议

### ISSUE THREAD

**Issue by ZhangSir9901** [qist/xray-ui#227]
现在脚本已经可以完成cf的ssl自动申请，申请完之后还需要手动重置ssl才可以应用使用。

因为cf在申请域名ssl的过程中，已经获得了ssl的证书和私钥地址，为什么不可以自动重置ssl呢？

建议在申请ssl成功结束后，自动提示，是否自动应用ssl，输入y，则自动应用，否则需要手动重置ssl

**Comment by qist** [comment]
更新一下`xray-ui update_shell` 或者 `xray-ui` 选择16 应该就可以了。

**Comment by ZhangSir9901** [comment]
> 更新一下`xray-ui update_shell` 或者 `xray-ui` 选择16 应该就可以了。

期待下次脚本更新。
