### ISSUE TITLE
请给出xhttp配置的多一些实例。谢谢。

### ISSUE THREAD

**Issue by ZhangSir9901** [qist/xray-ui#228]
xhttp已经添加了，但是配置不知道是具体要填写哪些东西的。希望作者给一些配置的实例。谢谢。

**Comment by qist** [comment]
https://xtls.github.io/config/transports/splithttp.html#xhttpobject 你看这个，配置任意选择或者默认都是可以使用的。

**Comment by ZhangSir9901** [comment]
非常感谢。。
