### ISSUE TITLE
建议默认取消服务器端的 geoip 和 geosite 机制

### ISSUE THREAD

**Issue by mulder125** [qist/xray-ui#28]
原因是最近遇到一个问题：部份境外站点无法代理 (Google Play, Yahoo 等)，使用pssswall, ssrp, clash情况相同
找了几天最后发现和节点有关，使用原版x-ui的节点就正常，使用此版xray-ui的节点就有问题
对比面板差异发现是因为此版xray-ui使用geoip 和 geosite 机制过滤导致部份境外站点无法正常走代理
最后我自行把面板设置->xray 相关设置 中的geoip 和 geosite 机制删除保存重启面板后就正常了

建议服务器端不要有此机制比较好，因为geoip 和 geosite 可能有误，geoip 和 geosite机制用在Client端比较合适
或者改为默认不使用，但保留geoip 和 geosite 机制可自行设定使用

最后感谢继续维护x-ui面板

**Comment by qist** [comment]
这样设置的目的防止vps IP被拉黑了。你可以参考这个修改https://github.com/qist/xray-ui/blob/main/wireguard.md 这样回国IP就使用cf的IP。保护vps暴露。

**Comment by mulder125** [comment]
因为目前有些geoip/geosite 归在CN实际是被墙的，默认都blocked会造成部份被墙站点无法访问

现在按你的思路让geoip/geosite 归在CN的都走CF的WARP IP出口，测试OK。
(但前提要VPS要先取得CF的WARP IP)

**Comment by qist** [comment]
下个版本把这些配置删除。

**Comment by GreatMichaelLee** [comment]
> 下个版本把这些配置删除。

别啊，这不是RPRX大佬推荐的保护vps的基本操作吗？？？归在CN仍然被block的，自己拧出来放proxy里就好啊！！

**Comment by qist** [comment]
@GreatMichaelLee  不影响已经有的版本，只是新版本安装的时候使用默认，觉得把CN block掉好点我就添加上去。

**Comment by mulder125** [comment]
> > @GreatMichaelLee 不影响已经部署版本，只是新版本安装的时候使用默认，觉得把CN block掉好点我就添加上去。
> 
> 我建议还是保留吧，放在cn里被block掉的无非就是那几个国内放在北京的几个googleapi服务器，这个geosite另有定义，可以自己再加优先规则选择proxy.而且一般都是要把这些api服务器用dns解析为国外服务器来配合使用较为安全，避免直接访问这些国内的谷歌服务器。你想你访问谷歌，大部分都fq,然后有些api流量又访问国内,那不是很奇怪吗

其实不只google在cn的服务器，实测yahoo系列也同样，可能还有其他站点有相同问题。
至于你题的问题可以都在Client端设定解决，但如果Server端已经block了，Client端再怎么设也无法存取被block的站点，造成使用者疑惑。

目前两个方式比较好：
1. Server端默认不block (不清楚这样是否容易被封，暂无研究)
2. Server端不要block某些归在CN的站点，而是设定CN站点由CF WARP IP出口
