### ISSUE TITLE
能不能在首页添加一键同时更新最新goeip和goesite的按钮

### ISSUE THREAD

**Issue by wcl20003000** [qist/xray-ui#29]
能不能在首页添加一键同时更新最新goeip和goesite的按钮

**Comment by qist** [comment]
更新到最新版本。

**Comment by GreatMichaelLee** [comment]
我觉得一键不一键到是次要的，能不能在显示xray-ui,xray版本的旁边，吧geoip/geosite的版本号也给显示出来，方便我查看上次距今是多久前更新的，因为数据版本号其实就是日期，另外，更新完成后看版本号日期也是个校验。现在感觉是盲的。

**Comment by qist** [comment]
点击更新后记录点击更新版本吧，没更新过就显示未曾更新。这个5.1后给弄上。

**Comment by GreatMichaelLee** [comment]
> @GreatMichaelLee 已经更新上去了。

赞，产品经理都不如你:P

**Comment by yzx1208** [comment]
赞就完了。
