### ISSUE TITLE
bug,每次升级被更改xray版本导致不通

### ISSUE THREAD

**Issue by GreatMichaelLee** [qist/xray-ui#30]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

为啥每次我升级脚本，就把我的内核给从1.8.1给我切回到1.7.5去了？？最近几个版本都是如此，能否保留用户自定义内核版本？1.7.5是release版本，麻烦检查一下这块逻辑是否有问题！

### Version of xray-ui

1.8.5

### xray-ui log reports or xray log

none

**Comment by qist** [comment]
已经修改了。下次不会覆盖了。

**Comment by wcl20003000** [comment]
应该让xray和geoip，geosite在升级的时候都不更新替换。

**Comment by qist** [comment]
整个已经修复了。以后只更新xray-ui 这个二进制文件

**Comment by qist** [comment]
先执行
```
    wget --no-check-certificate -O /usr/bin/xray-ui https://raw.githubusercontent.com/qist/xray-ui/main/xray-ui.sh
    chmod +x /usr/bin/xray-ui
```
