### ISSUE TITLE
遇到了错误

### ISSUE THREAD

**Issue by laosan1990515** [qist/xray-ui#33]
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x83b126]
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]: goroutine 11377 [running]:
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]: xray-ui/util/common.GetMyIpAddr()
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]:         /home/runner/work/xray-ui/xray-ui/util/common/network.go:13 +0x66
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]: xray-ui/web/job.(*StatsNotifyJob).GetsystemStatus(0xc00087d488)
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]:         /home/runner/work/xray-ui/xray-ui/web/job/stats_notify_job.go:145 +0x10e
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]: xray-ui/web/job.(*StatsNotifyJob).Run(0xc00087d488)
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]:         /home/runner/work/xray-ui/xray-ui/web/job/stats_notify_job.go:41 +0x4e
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]: created by github.com/robfig/cron/v3.(*Cron).startJob
Apr 27 11:07:01 k8l1pr1z.vm xray-ui[1657]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
Apr 27 11:07:01 k8l1pr1z.vm systemd[1]: xray-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 27 11:07:01 k8l1pr1z.vm systemd[1]: xray-ui.service: Failed with result 'exit-code'.
Apr 27 11:42:33 k8l1pr1z.vm systemd[1]: Started xray-ui Service.
Apr 27 11:42:33 k8l1pr1z.vm xray-ui[9372]: 2023/04/27 11:42:33 xray-ui 1.8.6
Apr 27 11:42:33 k8l1pr1z.vm xray-ui[9372]: 2023/04/27 11:42:33 INFO - web server run http on [::]:55555
Apr 27 11:42:33 k8l1pr1z.vm xray-ui[9372]: 2023/04/27 11:42:33 INFO - telegram service ready to run
Apr 27 11:42:33 k8l1pr1z.vm xray-ui[9372]: 2023/04/27 11:42:33 INFO - TelegramService 
使用的一键安装，两个不同的VPS中都存在这种问题，请问是我的使用方式有错误吗？

**Comment by qist** [comment]
你的操作系统版本

**Comment by laosan1990515** [comment]
那我该使用什么操作系统呀大佬

**Comment by qist** [comment]
常用的系统都可以，内核版本大于3以上就可以了。

**Comment by laosan1990515** [comment]
好的谢谢大佬，我看看去。

**Comment by qist** [comment]
https://api64.ipify.org  http://ip.cip.cc 这两个你服务器能打开么

**Comment by laosan1990515** [comment]
第一个可以，第二个无法访问curl: (6) Could not resolve host: ip.cip.cc

**Comment by laosan1990515** [comment]
从下午一点钟运行到现在，没有出现过问题。使用的是Debian10 X64系统

**Comment by qist** [comment]
这个是获取IP 地址的时候访问不到报错。现在还是不能启动么。

**Comment by laosan1990515** [comment]
不知道在什么情况下会出现错误，必须手动重启。

**Comment by qist** [comment]
把对外访问的接口给关闭了把，反正用处也不大。

**Comment by laosan1990515** [comment]
好的，我尝试一下

**Comment by qist** [comment]
![image](https://user-images.githubusercontent.com/7844620/234790616-b0c66c07-0596-4224-b739-ac7244d7d61a.png)
 var ip string
 ip = common.GetMyIpAddr()
 status += fmt.Sprintf("IP地址:%s\r\n \r\n", ip)

**Comment by laosan1990515** [comment]
Linux version 4.19.0-19-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 4.19.232-1 (2022-03-07)

**Comment by qist** [comment]
或者你拉最新代码我把没用的ip 接口改成自己的了。
