### ISSUE TITLE
一直有大量的下行，导致服务器崩溃，重启关闭都没有，都有大量的下行

### ISSUE THREAD

**Issue by xiaodo2099** [qist/xray-ui#34]
![image](https://user-images.githubusercontent.com/129565310/235033994-90eaba0c-897e-4b73-9a16-780c861d7f5c.png)

**Comment by qist** [comment]
你看看你得入站列表流量大么。我看这个截图流量很少得。你看看你得网卡上传怎么大，你用iftop 监控看看是那个程序导致得。

**Comment by xiaodo2099** [comment]
就是只装了这一个程序

**Comment by xiaodo2099** [comment]
![image](https://user-images.githubusercontent.com/129565310/235034892-e06d9349-8324-47dc-b91d-f791f3fa8aa1.png)
我全部都关了，都没有用，只能是重装系统了，我有点晕

**Comment by xiaodo2099** [comment]
![image](https://user-images.githubusercontent.com/129565310/235034997-1e567ff3-8b0d-462e-88d9-b9ff19be0506.png)

**Comment by qist** [comment]
那你用iftop 监控看看先

**Comment by xiaodo2099** [comment]
![image](https://user-images.githubusercontent.com/129565310/235035909-05955d6b-36a0-42ac-942d-c443f8f64e54.png)

**Comment by qist** [comment]
ss -tnpuoe| grep ESTAB

**Comment by qist** [comment]
![image](https://user-images.githubusercontent.com/7844620/235036003-43dd14c0-a8ab-4e50-be49-fb3cb1967919.png)
搜一下这个IP 是那个进程连接得。

**Comment by xiaodo2099** [comment]
好的

**Comment by qist** [comment]
ss -tnpuoe| grep ESTAB | grep 23.231.184.246

**Comment by xiaodo2099** [comment]
![image](https://user-images.githubusercontent.com/129565310/235036238-fdeddc95-631c-4956-ad7e-9d98734ff5cc.png)

**Comment by xiaodo2099** [comment]
![image](https://user-images.githubusercontent.com/129565310/235036284-61da0e62-a098-4189-9032-e28840a8858a.png)

**Comment by xiaodo2099** [comment]
![image](https://user-images.githubusercontent.com/129565310/235036463-85875a6d-506d-4fdb-992a-2e792fde813f.png)
第一个ip 一直在变

**Comment by xiaodo2099** [comment]
113.13 是，54.36不是

**Comment by xiaodo2099** [comment]
![image](https://user-images.githubusercontent.com/129565310/235037168-ea3e6066-ea9b-4f60-b90e-363f8c62a1ae.png)
只有第一个是我的113.13

**Comment by qist** [comment]
iftop -P -N 然后按小n 看看连接端口

**Comment by xiaodo2099** [comment]
![image](https://user-images.githubusercontent.com/129565310/235037706-7b9a37b2-9e6c-423d-a3b9-b2b7983c4379.png)

**Comment by qist** [comment]
last 查看登陆IP  cat  ~/.ssh/authorized_keys 查看有没异常得密钥 ll /home/ 查看有没异常得用户目录 cat  /etc/passwd 查看有没异常用户。感觉你服务器中木马了。记得限制ssh 指定IP 登陆 可以删除使用账号密码登陆只能使用密钥登陆fail2ban 配置ssh错误登陆拦截。

**Comment by xiaodo2099** [comment]
嗯嗯，明白了

**Comment by qist** [comment]
ps -ef | grep ygljglkjgfg 看看这个东西

**Comment by xiaodo2099** [comment]
![image](https://user-images.githubusercontent.com/129565310/235038428-be4ec40a-5278-4dfb-8952-fc5b2f23552f.png)

**Comment by qist** [comment]
![image](https://user-images.githubusercontent.com/7844620/235038680-fb2773f2-4d60-4380-b9f6-7cdb3348ee21.png)
你得ps 应该是被修改了得。which ps  查看是否二进制 less /usr/bin/ps

**Comment by qist** [comment]
ygljglkjgfg0  这个是一个ddos 病毒。

**Comment by qist** [comment]
内核必须保持最新状态，ssh 端口做好IP 限制。别账号密码登陆。

**Comment by xiaodo2099** [comment]
嗯嗯，谢谢，我自己去修改了，辛苦了
