### ISSUE TITLE
Nginx前置SNI分流问题以及目前遇到的问题

### ISSUE THREAD

**Issue by facebook20146** [qist/xray-ui#40]
1、Nginx前置SNI分流 
没做nginx 代理时必须打开sockopt 下面的acceptProxyProtocol 
如果使用nginx 转发过例如 grpc ws 不需要开启acceptProxyProtocol
（1）这句话不理解是什么意思。比如我现在没有申请域名，没有证书的情况下，使用vless reality tcp/ h2/ grpc这几种节点方式，acceptproxyprotocol用打开吗
（2）不通类型的reality的dest不能使用同一个域名吗，比如都使用微软的

2、使用reality目前遇到的问题（纯IP地址，没有证书，域名,手机v2rayng,家里路由ssrplus,都是1.8.0以上内核）
（1）vless reality tcp
搭建完成后，可以ping通，一连接，无法使用，v2rayng进行tcpping提示net/ http tls handshake timed out，然后这会再去打开面板，面板就打不开了。再次tcp ping节点，显示-1
（2）vless reality h2
ssrplus显示一天中有几次错误，自动换到其他节点，过一会又自己换回来，有时ping不通，而且感觉高一些
（3）vless reality grpc
目前用了几个小时，暂无明显问题

**Comment by qist** [comment]
nginx前置，acceptproxyprotocol都要开启，不然收的IP就是127.0.0.1这样的。域名一样他不知道发个协议去吧！你开起多协议的话。nosni 可以tcp 跟h2或者grpc 有一个要指定域名分流fb哪里配置。tcp 跟另外一个不需要域名或者相同域名。

**Comment by qist** [comment]
dest 选择支持tls1.3的。国外政府跟企业域名。下面的servername随便写。

**Comment by qist** [comment]
没做nginx 代理不要开启，不然可能出现连接不了的问题。

**Comment by qist** [comment]
1、Nginx前置SNI分流 没做nginx 代理时必须打开sockopt 下面的acceptProxyProtocol 如果使用nginx 转发过例如 grpc ws 不需要开启acceptProxyProtocol 

> 前置没有用nginx tcp sni 代理就不需要开启acceptProxyProtocol   你grpc ws 用nginx 做过转发就不要开启acceptProxyProtocol   

（1）这句话不理解是什么意思。比如我现在没有申请域名，没有证书的情况下，使用vless reality tcp/ h2/ grpc这几种节点方式，acceptproxyprotocol用打开吗 .

>没有nginx 转发就不需要开启acceptProxyProtocol  如果公用端口然后nginx 转发了就必须开启acceptProxyProtocol   

（2）不通类型的reality的dest不能使用同一个域名吗，比如都使用微软的

> 端口不一致可以使用相同域名 公用端口无法sni 分流就别公用域名了

 2、使用reality目前遇到的问题（纯IP地址，没有证书，域名,手机v2rayng,家里路由ssrplus,都是1.8.0以上内核） （1）vless reality tcp 搭建完成后，可以ping通，一连接，无法使用，v2rayng进行tcpping提示net/ http tls handshake timed out，然后这会再去打开面板，面板就打不开了。再次tcp ping节点，显示-1 

> tcp 模式记得开启  flow  没转发别开启acceptProxyProtocol  然后dest记得使用政府部门获取企业支持1.3的域名跟IP


（2）vless reality h2 ssrplus显示一天中有几次错误，自动换到其他节点，过一会又自己换回来，有时ping不通，而且感觉高一些 （3）vless reality grpc 目前用了几个小时，暂无明显问题

> 请选好dest记得使用政府部门获取企业支持1.3的域名跟IP 然后 serverNames 可以随便填写。

**Comment by facebook20146** [comment]
> 1、Nginx前置SNI分流 没做nginx 代理时必须打开sockopt 下面的acceptProxyProtocol 如果使用nginx 转发过例如 grpc ws 不需要开启acceptProxyProtocol
> 
> > 前置没有用nginx tcp sni 代理就不需要开启acceptProxyProtocol   你grpc ws 用nginx 做过转发就不要开启acceptProxyProtocol
> 
> （1）这句话不理解是什么意思。比如我现在没有申请域名，没有证书的情况下，使用vless reality tcp/ h2/ grpc这几种节点方式，acceptproxyprotocol用打开吗 .
> 
> > 没有nginx 转发就不需要开启acceptProxyProtocol  如果共用端口然后nginx 转发了就必须开启acceptProxyProtocol
> 
> （2）不通类型的reality的dest不能使用同一个域名吗，比如都使用微软的
> 
> > 端口不一致可以使用相同域名 共用端口无法sni 分流就别共用域名了
> 
> 2、使用reality目前遇到的问题（纯IP地址，没有证书，域名,手机v2rayng,家里路由ssrplus,都是1.8.0以上内核） （1）vless reality tcp 搭建完成后，可以ping通，一连接，无法使用，v2rayng进行tcpping提示net/ http tls handshake timed out，然后这会再去打开面板，面板就打不开了。再次tcp ping节点，显示-1
> 
> > tcp 模式记得开启  flow  没转发别开启acceptProxyProtocol  然后dest记得使用政府部门或者企业支持1.3的域名跟IP
> 
> （2）vless reality h2 ssrplus显示一天中有几次错误，自动换到其他节点，过一会又自己换回来，有时ping不通，而且感觉高一些 （3）vless reality grpc 目前用了几个小时，暂无明显问题
> 
> > 请选好dest记得使用政府部门或者企业支持1.3的域名跟IP 然后 serverNames 可以随便填写。
> > 微软 苹果 1.1.1.1 这些用太多了断流很多。

谢谢回复
dest网站确定没有问题。之前用了好几个面板，都出现了net http tls handshake timedout问题，不知道是不是服务器的问题，我使用的是centos8，之前安装过其他面板。大佬有群吗

**Comment by qist** [comment]
群没有，你可以发截图 然后看看你服务端 跟客户端么，然后数据脱敏。

**Comment by facebook20146** [comment]
> 群没有，你可以发截图 然后看看你服务端 跟客户端么，然后数据脱敏。

不太懂什么意思，是去看服务器的日志跟客户端日志吗

**Comment by qist** [comment]
看配置
![image](https://github.com/qist/xray-ui/assets/7844620/78f5bc80-1ffe-4d81-8a81-ab9a7787ba1f)
这个是我开启了前置分流配置
![image](https://github.com/qist/xray-ui/assets/7844620/46646a07-a403-4298-bfc8-c68b4c557a21)
下面是客户端配置
客户端如果你没转发你可以直接复制链接或者扫描二维码应该就可以用的。

**Comment by facebook20146** [comment]
![1-1](https://github.com/qist/xray-ui/assets/132545338/8e5f3244-9d97-4629-a3b7-db1869a24967)
![1-2](https://github.com/qist/xray-ui/assets/132545338/fb4a9075-df31-4ca6-9fd3-8dacb7ae0017)
![2-1](https://github.com/qist/xray-ui/assets/132545338/1344f0a4-419f-4a3b-b80b-84b806bc34df)
![2-2](https://github.com/qist/xray-ui/assets/132545338/cf47a080-22bb-4ffd-9b99-30fee3315846)
第一个是h2的，第二个是tcp的，应该没问题吧，客户端刚才用v2rayn试了下，目前没啥问题

**Comment by qist** [comment]
现在两个都正常了么。这个是没问题的。

**Comment by facebook20146** [comment]
> 现在两个都正常了么。这个是没问题的。

目前h2和TCP正常了，grpc那个目前没问题，谢谢大佬，有问题再问大佬，不知道你有没有电报号，还想加一下你，如果你不方便公布，我把我的给你，t.me/Song202210，大佬如果不方便，告诉一声，我把这条和上面配置的删除

**Comment by qist** [comment]
我没申请tg

**Comment by facebook20146** [comment]
> 我没申请tg

好的，以后有问题在这里联系大佬
