### ISSUE TITLE
能否在shell菜单里加一个更新到最新geo数据的选项

### ISSUE THREAD

**Issue by GreatMichaelLee** [qist/xray-ui#41]
用户选择该选项更新，就提示当前系统正在用的geosite,geoip版本，以及显示最新geosite,geoip版本，问用户是否选择更新（y/N),不用web里那样选择版本，（我一直没搞明白，提供那么多geo数据日期的版本供选择有啥意义，不都是最新的才用么）

**Comment by GreatMichaelLee** [comment]
主要是我登录shell比较多，web用的比较少

**Comment by fireinrain** [comment]
一般不都是设置定时任务 自动更新吗 这东西一般人不回去看 最好做到无感知 在安装的时候 就可以设置定时更新geodata

**Comment by qist** [comment]
已经更新了你可以使用xray-ui geoip 或者 cd /usr/local/xray-ui/  ./xray-ui geoip 进行更新，你可以配置定时任务等更新。

**Comment by facebook20146** [comment]
> 已经更新了你可以使用xray-ui geoip 或者 cd /usr/local/xray-ui/ ./xray-ui geoip 进行更新，你可以配置定时任务等更新。

定时更新命令大佬能发一下吗

**Comment by qist** [comment]
如果您想在每天凌晨 1:30 执行 "xray-ui geoip" 命令，您可以使用以下 Cron 表达式：

```
30 1 * * * xray-ui geoip
```
上面的表达式将在每天凌晨 1:30 执行 "xray-ui geoip" 命令。您可以将这个表达式添加到您的计划任务配置中，具体的配置方法可能因您所使用的操作系统而有所不同。

如果您是在类Unix系统上使用 Cron，您可以通过运行以下命令编辑计划任务配置：

```
crontab -e
```
然后，将上面的表达式添加到打开的编辑器中，并保存退出。这将会将您的命令添加到 Cron 中，以便每天凌晨 1:30 自动执行。

**Comment by GreatMichaelLee** [comment]
> 30 1 * * * xray-ui geoip

这个命令在shell里直接运行不会退出，还让你按一个什么返回键，又还要回到主菜单，能否不要这么设计，不清楚如果crontab每天这么运行，会不会crontab会累积process, 能否运行完这个就直接一揽子吧重启面板也做完然后exit释放?

**Comment by qist** [comment]
你更新一下xray-ui shell 文件 已经修复这个问题了

**Comment by facebook20146** [comment]
> 如果您想在每天凌晨 1:30 执行 "xray-ui geoip" 命令，您可以使用以下 Cron 表达式：
> 
> ```
> 30 1 * * * xray-ui geoip
> ```
> 
> 上面的表达式将在每天凌晨 1:30 执行 "xray-ui geoip" 命令。您可以将这个表达式添加到您的计划任务配置中，具体的配置方法可能因您所使用的操作系统而有所不同。
> 
> 如果您是在类Unix系统上使用 Cron，您可以通过运行以下命令编辑计划任务配置：
> 
> ```
> crontab -e
> ```
> 
> 然后，将上面的表达式添加到打开的编辑器中，并保存退出。这将会将您的命令添加到 Cron 中，以便每天凌晨 1:30 自动执行。

在centos, Ubuntu里面是不是运行这个“30 1 * * * xray-ui geoip"，直接切换到root用户就行了嘛，不需要其他操作吧，感谢回答

**Comment by qist** [comment]
crontab -e 然后添加 30 1 * * * xray-ui geoip 保存推出就是了

**Comment by facebook20146** [comment]
> crontab -e 然后添加 30 1 * * * xray-ui geoip 保存推出就是了

谢谢，我搜了下，退出保存是“:wq”就行了吧，只能照猫画虎的小白来提问了😃

**Comment by yzx1208** [comment]
隔壁vasma也是最近增加了这个自动geo的功能，自动添加定时任务。

**Comment by facebook20146** [comment]
![IMG_20230526_230535](https://github.com/qist/xray-ui/assets/132545338/0fd52250-8966-4e3b-ac36-19027df5b3dd)
![IMG_20230526_230451](https://github.com/qist/xray-ui/assets/132545338/e72a4c0c-7577-4034-92d0-b31ec969a265)
大佬，这算加上了吗，Ubuntu
还有一个centos，更不会用，咋弄

**Comment by facebook20146** [comment]
> crontab -e 然后添加 30 1 * * * xray-ui geoip 保存推出就是了

大佬，辛苦看一下上面回复

**Comment by qist** [comment]
#是注释的意思。不起作用。生效没有你看看crontab -l 看看显示什么。

**Comment by facebook20146** [comment]
> #是注释的意思。不起作用。生效没有你看看crontab -l 看看显示什么。

这是不是不对
![IMG_20230528_134054](https://github.com/qist/xray-ui/assets/132545338/d4cbd148-e1ba-4443-8771-3ff7e92ef9ee)

**Comment by qist** [comment]
是的。#是说明的意思。注释了。删除#

**Comment by facebook20146** [comment]
> 是的。#是说明的意思。注释了。删除#

弄了好像也不行，大佬能不能把定时任务加到脚本里，自己加一个，小白真的不会
![IMG_20230528_135147](https://github.com/qist/xray-ui/assets/132545338/155fb7c1-2bb1-4c7b-a4a9-68cbc56d8cbd)

**Comment by facebook20146** [comment]
centos那个更不会了😭

**Comment by qist** [comment]
u系统没有d systemctl status cron 上班的时候我添加吧！

**Comment by facebook20146** [comment]
> u系统没有d systemctl status cron 上班的时候我添加吧！

谢谢大佬，等你好消息

**Comment by GreatMichaelLee** [comment]
建议学习一下再来，这个基础的不能再基础了…



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月28日(周日) 中午1:53
收件人: ***@***.***&gt;;
抄送: "michael ***@***.******@***.***&gt;;
主题: Re: [qist/xray-ui] 能否在shell菜单里加一个更新到最新geo数据的选项 (Issue #41)




 
centos那个更不会了😭

**Comment by qist** [comment]
```
# 更新最新的shell
xray-ui update_shell
# 添加到定时任务
xray-ui crontab
# 查看是否添加成功
cat /etc/crontab
```

**Comment by facebook20146** [comment]
> ```
> # 更新最新的shell
> xray-ui update_shell
> # 添加到定时任务
> xray-ui crontab
> # 查看是否添加成功
> cat /etc/crontab
> ```

谢谢大佬

**Comment by qist** [comment]
然后把你自己添加的删除。别重复了。

**Comment by facebook20146** [comment]
> 然后把你自己添加的删除。别重复了。

都没加上估计😃

**Comment by facebook20146** [comment]
> > ```
> > # 更新最新的shell
> > xray-ui update_shell
> > # 添加到定时任务
> > xray-ui crontab
> > # 查看是否添加成功
> > cat /etc/crontab
> > ```
> 
> 谢谢大佬

大佬，这算是加上自动任务了吗
![IMG_20230531_081844](https://github.com/qist/xray-ui/assets/132545338/2d51f340-8428-4057-8a6d-f59805457fa1)

**Comment by qist** [comment]
是的已经加上了。

**Comment by facebook20146** [comment]
> 是的已经加上了。

辛苦大佬
