### ISSUE TITLE
希望添加一个批量添加cloudflare的优选IP界面，配合cdn使用

### ISSUE THREAD

**Issue by yzx1208** [qist/xray-ui#43]
希望添加一个批量添加cloudflare的优选IP界面，配合cdn使用

**Comment by qist** [comment]
怎么各使用方法。不是很懂。

**Comment by Misaka-blog** [comment]
优选IP一般都是在本地进行的吧，在服务器上优选参考不大

**Comment by yzx1208** [comment]
其实你可以看看vasma，能够将本地优选的ip，作为一个列表，全部添加到vps。vps生成的订阅链接是由基础链接和vps链接组合完成。实现了一个vps订阅，一下就可以使用无数的cdn

**Comment by yzx1208** [comment]
大佬，有教程么？

**Comment by qist** [comment]
@yzx1208  等下我些一个把

**Comment by yzx1208** [comment]
或者说给vps自动配置这个功能。手里有多台vps，到时可以操作下。

**Comment by qist** [comment]
这些vps 要在国内的。国外明显不可以的。面板直接写cf IP可能ip 被封还是要手动替换。用dns 方案自动更新ip更好。

**Comment by qist** [comment]
你可以看看这个文件把： https://github.com/qist/xray-ui/blob/main/Cloudflare%E4%BC%98%E9%80%89IP.md

**Comment by yzx1208** [comment]
好的，我试试看。
