### ISSUE TITLE
database is locked是什么意思

### ISSUE THREAD

**Issue by GreatMichaelLee** [qist/xray-ui#46]
xray-ui 经常打印数据库被锁住，是什么意思啊

May 23 04:53:08  xray-ui[1901]: 2023/05/23 04:53:08 WARNING - disable invalid inbounds err: database is locked
May 23 06:15:38  xray-ui[1901]: 2023/05/23 06:15:38 WARNING - disable invalid inbounds err: database is locked
May 23 06:27:04 xray-ui[1901]: 2023/05/23 06:26:53 WARNING - add traffic failed: database is locked
May 23 06:27:04  xray-ui[1901]: 2023/05/23 06:27:03 WARNING - add traffic failed: database is locked
May 23 06:29:09  xray-ui[1901]: 2023/05/23 06:29:05 WARNING - add traffic failed: database is locked
May 23 06:29:14  xray-ui[1901]: 2023/05/23 06:29:13 WARNING - add traffic failed: database is locked
May 23 07:29:23  xray-ui[1901]: 2023/05/23 07:29:23 WARNING - add traffic failed: database is locked
May 23 09:00:08  xray-ui[1901]: 2023/05/23 09:00:08 WARNING - disable invalid inbounds err: database is locked
May 23 09:00:13  xray-ui[1901]: 2023/05/23 09:00:13 WARNING - add traffic failed: database is locked
May 23 09:05:33  xray-ui[1901]: 2023/05/23 09:05:33 WARNING - add traffic failed: database is locked

**Comment by qist** [comment]
你配置了电报机器人么，还是在做什么操作出现的,是你自己编译的版本么。我这个没出现过这个问题。

**Comment by GreatMichaelLee** [comment]
> 你配置了电报机器人么，还是在做什么操作出现的,是你自己编译的版本么。我这个没出现过这个问题。

我没配电报机器人也不是自己编译的，用的你的版本啊，数据库文件是哪个在哪个目录下？我删掉试试

**Comment by qist** [comment]
这个目录 /etc/xray-ui/xray-ui.db

**Comment by GreatMichaelLee** [comment]
sqlite3 xray-ui.db '.clone xray-ui-new.db'
mv xray-ui.db xray-ui-old.db
mv xray-ui-new.db xray-ui.db

然后重装一下解决readonly的问题，就解决了。
