### ISSUE TITLE
更新后，xray启动失败

### ISSUE THREAD

**Issue by facebook20146** [qist/xray-ui#54]
如题，大佬，怎么解决。
如果只能重装，怎么保存数据重装
![IMG_20230606_124728](https://github.com/qist/xray-ui/assets/132545338/1efba69d-639c-44fa-8d2a-3a9b80c0d34d)

**Comment by qist** [comment]
journalctl -u xray-ui  看看日志

**Comment by qist** [comment]
数据存储位置/etc/xray-ui/xray-ui.db 可以手动备份一下。

**Comment by facebook20146** [comment]
> journalctl -u xray-ui 看看日志

![IMG_20230606_125655](https://github.com/qist/xray-ui/assets/132545338/1948eb03-311c-4c6f-9f83-be180ee2dff4)

**Comment by facebook20146** [comment]
> 数据存储位置/etc/xray-ui/xray-ui.db 可以手动备份一下。

我用finalshell看能不能下载下来

**Comment by qist** [comment]
你看看进程还在不

**Comment by facebook20146** [comment]
> 你看看进程还在不 ` xray-ui stop` `cd /usr/local/xray-ui/` `./xray-ui` 看看报错问题

![Uploading IMG_20230606_130405.jpg…]()

**Comment by facebook20146** [comment]
> 你先别重新安装看看什么原因造成我都是测试过的。 ` xray-ui stop` `cd /usr/local/xray-ui/` `./xray-ui` 看看报错问题

![IMG_20230606_130405](https://github.com/qist/xray-ui/assets/132545338/49975dfa-789f-4d72-a25f-f0a0da5433f1)

**Comment by qist** [comment]
退出然后这样启动看看
`xray-ui start `

**Comment by facebook20146** [comment]
> 退出然后这样启动看看 `xray-ui start `

![IMG_20230606_130845](https://github.com/qist/xray-ui/assets/132545338/4df1bf8b-e35d-47b6-9198-5c7f174166d9)

**Comment by qist** [comment]
```
 systemctl status xray-ui.service
cat /etc/systemd/system/xray-ui.service
```
看看问题启动内容

**Comment by facebook20146** [comment]
> ```
> systemctl status network.target
> 
>  systemctl status xray-ui.service
> cat /etc/systemd/system/xray-ui.service
> ```
> 
> 看看问题启动内容

![IMG_20230606_131549](https://github.com/qist/xray-ui/assets/132545338/714d228e-db83-4a9b-ae47-b93ea6e40521)
大佬，你有邮箱吗，不行我把秘钥和IP发你，你帮我看下

**Comment by qist** [comment]
你操作系统内核是多少 
`systemctl --version` 
然你看看你还有吗其它systemctl 启动 程序可以重启的试试重启是否成功

**Comment by qist** [comment]
```
[Unit]
Description=xray-ui Service
After=network.target
Wants=network.target

[Service]
Type=simple
WorkingDirectory=/usr/local/xray-ui/
ExecStart=/usr/local/xray-ui/xray-ui

[Install]
WantedBy=multi-user.target
```
文件内容 怎么少东西了

**Comment by facebook20146** [comment]
> ```
> [Unit]
> Description=xray-ui Service
> After=network.target
> Wants=network.target
> 
> [Service]
> Type=simple
> WorkingDirectory=/usr/local/xray-ui/
> ExecStart=/usr/local/xray-ui/xray-ui
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> 文件内容 怎么少东西了

我打开了finalshell，怎么加上这个

**Comment by facebook20146** [comment]
> 你操作系统内核是多少 `systemctl --version` 然你看看你还有吗其它systemctl 启动 程序可以重启的试试重启是否成功

![IMG_20230606_132054](https://github.com/qist/xray-ui/assets/132545338/30ab460c-792f-46aa-86ae-6e6176f65ecb)

**Comment by qist** [comment]
```
cd /usr/local/xray-ui
cat  xray-ui.service
# 如果有
cp -f xray-ui.service /etc/systemd/system/
  systemctl daemon-reload
  systemctl enable xray-ui
  xray-ui restart
```

**Comment by facebook20146** [comment]
> ```
> cd /usr/local/xray-ui
> cat  xray-ui.service
> # 如果有
> cp -f xray-ui.service /etc/systemd/system/
>   systemctl daemon-reload
>   systemctl enable xray-ui
>   xray-ui restart
> ```

![IMG_20230606_132805](https://github.com/qist/xray-ui/assets/132545338/cb53865f-1608-42c3-a11c-09306b5d9f83)

**Comment by facebook20146** [comment]
> ```
> cd /usr/local/xray-ui
> cat  xray-ui.service
> # 如果有
> cp -f xray-ui.service /etc/systemd/system/
>   systemctl daemon-reload
>   systemctl enable xray-ui
>   xray-ui restart
> ```

大佬，方便给我邮箱吗，我把配置给你，你帮我看看，十分感谢

**Comment by qist** [comment]
juestnow@gmail.com

**Comment by facebook20146** [comment]
> [juestnow@gmail.com](mailto:juestnow@gmail.com)

已发，大佬

**Comment by facebook20146** [comment]
> ```
> cd /usr/local/xray-ui
> cat  xray-ui.service
> # 如果有
> cp -f xray-ui.service /etc/systemd/system/
>   systemctl daemon-reload
>   systemctl enable xray-ui
>   xray-ui restart
> ```

刚才忘了用户名，又发了一下

**Comment by facebook20146** [comment]
> ```
> cd /usr/local/xray-ui
> cat  xray-ui.service
> # 如果有
> cp -f xray-ui.service /etc/systemd/system/
>   systemctl daemon-reload
>   systemctl enable xray-ui
>   xray-ui restart
> ```
麻烦大佬了，有事及时联系

**Comment by qist** [comment]
你把 SELINUX=enforcing 关闭把。

**Comment by facebook20146** [comment]
> 你把 SELINUX=enforcing 关闭把。

大佬能不能帮着弄一下，我刚下楼，手里没电脑，如果不方便，麻烦告诉我命令，我一会弄

**Comment by qist** [comment]
已经启动了
```
临时关闭
sudo setenforce 0
永久关闭
修改文件
/etc/sysconfig/selinux

SELINUX=disabled
```

**Comment by facebook20146** [comment]
> 已经启动了
> 
> ```
> 临时关闭
> sudo setenforce 0
> 永久关闭
> 修改文件
> /etc/sysconfig/selinux
> 
> SELINUX=disabled
> ```

现在xray已经正常了吗
然后关闭这个就行了，是吗

**Comment by qist** [comment]
是的已经正常启动了。

**Comment by facebook20146** [comment]
> > 已经启动了
> > ```
> > 临时关闭
> > sudo setenforce 0
> > 永久关闭
> > 修改文件
> > /etc/sysconfig/selinux
> > 
> > SELINUX=disabled
> > ```
> 
> 现在xray已经正常了吗 然后关闭这个就行了，是吗



> 已经启动了
> 
> ```
> 临时关闭
> sudo setenforce 0
> 永久关闭
> 修改文件
> /etc/sysconfig/selinux
> 
> SELINUX=disabled
> ```

这个如果开着，影响正常使用吗，如果不影响我就不动了，因为自己真的不懂这些代码，怕又弄坏了，还得麻烦大佬

**Comment by qist** [comment]
其它软件启动还是会启动不了。

**Comment by qist** [comment]
cat /etc/selinux/config 
SELINUX=disabled

**Comment by qist** [comment]
> > cat /etc/selinux/config SELINUX=disabled 这样就可以了
> 
> 这俩行是一个命令吗，还是分两次执行
cat /etc/selinux/config 查看文件内容 
SELINUX=disabled  是文件内容

**Comment by facebook20146** [comment]
> > > cat /etc/selinux/config SELINUX=disabled 这样就可以了
> > 
> > 
> > 这俩行是一个命令吗，还是分两次执行
> > cat /etc/selinux/config 查看文件内容
> > SELINUX=disabled  是文件内容

谢谢大佬，我看你又更新代码了，太勤奋了
