### ISSUE TITLE
xray-ui 1.8.1在进行升级后无法对入站进行编辑或者添加入站

### ISSUE THREAD

**Issue by waaaaaaaaagh** [qist/xray-ui#6]
如题所示，通过SSH连接后升级xray-ui，但无法进行编辑入站协议或添加入站协议，但面板其他部分可正常使用

**Comment by qist** [comment]
强制刷新 ctrl+f5

**Comment by waaaaaaaaagh** [comment]
系统为Ubuntu20.04LTS 架构AMD

**Comment by waaaaaaaaagh** [comment]
> 强制刷新 ctrl+f5

已经在浏览器中进行刷新了，还是未起作用，其他直接安装最新版的VPS还能够使用，但是更新后了的反而不行

**Comment by qist** [comment]
更换一个浏览器，或者F12 调试看看报错是什么。

**Comment by waaaaaaaaagh** [comment]
> 更换一个浏览器，或者F12 调试看看报错是什么。
我默认使用Firefox浏览器进行操作，刚换了Chrome系的就可以了，谢谢大佬
