### ISSUE TITLE
全局使用了搭建的ss代理后，无法连接第三方http代理

### ISSUE THREAD

**Issue by ShotoZhao** [qist/xray-ui#66]
本地流量全局使用搭建的ss代理，但是无法连接第三方的http代理。
比如，chrome的switchyomega中使用第三方的http代理，无法连接。

**Comment by qist** [comment]
v2rayN 能拨号上去系统代理能链接不。是不是根本就没连接到服务器。 http代理 允许局域网访问没。等等。

**Comment by ShotoZhao** [comment]
> v2rayN 能拨号上去系统代理能链接不。是不是根本就没连接到服务器。 http代理 允许局域网访问没。等等。

我用第三方的socks代理是可以连的，就http的代理不能连。
我用其他实现的ss代理（比如go-shadowsock2），可以使用http代理。

**Comment by qist** [comment]
你用那个客户端工具http 怎么配置的。socks 端口与http 端口是分开的不一样的。

**Comment by ShotoZhao** [comment]
> 你用那个客户端工具http 怎么配置的。socks 端口与http 端口是分开的不一样的。你可以把http 端口修改一下是不是端口没启起来。http 端口通么。

ss代理是运行在软路由上的ssrp中的，ssrp设置了全局代理

**Comment by ShotoZhao** [comment]
> > 你用那个客户端工具http 怎么配置的。socks 端口与http 端口是分开的不一样的。你可以把http 端口修改一下是不是端口没启起来。http 端口通么。
> 
> ss代理是运行在软路由上的ssrp中的，ssrp设置了全局代理

所以我本地电脑的所有流量都是经过软路由的ss代理的。本地连接第三方的http代理不行，chrome的switchyomega中使用http代理失败，换成sock5代理是可以连的。

ss的服务端换成go-shadowsock2是可以使用http代理的。

**Comment by qist** [comment]
你的http 代理ip 是外网可以访问还是内网IP还是国内ip么。ss 代理没做内外分流么。

**Comment by qist** [comment]
![image](https://github.com/qist/xray-ui/assets/7844620/1f6db651-5af0-4222-ac50-977d64d74664)
```
{
  "log": {
    "access": "none",
    "error": "none",
    "loglevel": "info"
  },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "blocked"
    }
  ],
  "policy": {
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    },
    "levels": {
      "0": {
        "handshake": 2,
        "connIdle": 120,
        "uplinkOnly": 1,
        "downlinkOnly": 1
      }
    }
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "type": "field",
        "domain": [
          "www.gstatic.com"
        ],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads-all",
          "geosite:cn",
          "geosite:geolocation-cn"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "blocked"
      }
    ]
  },
  "stats": {}
}
```
# 拦截国内ip 不允许访问。你可以修改这个看看
```
  {
        "type": "field",
        "domain": [
          "geosite:category-ads-all",
          "geosite:cn",
          "geosite:geolocation-cn"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "blocked"
      }
```

**Comment by ShotoZhao** [comment]
> 你的http 代理ip 是外网可以访问还是内网IP还是国内ip么。ss 代理没做内外分流么。

不需要做分流，我希望全部流量都由ss代理出去。就是说，我本地的http代理 也是通过这个ss代理出去。
举例：
本地chrome+http三方代理 ---> ss代理 ---> google.com
最终请求谷歌的ip是本地的这个http代理ip，ss代理只是作为中转

**Comment by qist** [comment]
```
 {
        "type": "field",
        "domain": [
          "geosite:category-ads-all",
          "geosite:cn",
          "geosite:geolocation-cn"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "blocked"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "blocked"
      }
```

你把这个删除把或者改成 blocked 改成  direct

**Comment by ShotoZhao** [comment]
> 

改成direct或删了，都还是不行。

**Comment by qist** [comment]
```
   "loglevel": "info"
    "access": "none",
    "error": "none",
   修改一下
    "loglevel": "debug"
    "access": "/var/log/xray-access.log",
    "error": "/var/log/xray-error.log",
```
然后看看日志你的xray 版本是多少你可以升级到最新看看

**Comment by ShotoZhao** [comment]
> "loglevel": "debug"
>     "access": "/var/log/xray-access.log",
>     "error": "/var/log/xray-error.log",

我昨天才用你的脚本安装的，版本应该是最新的吧

**Comment by qist** [comment]
打包是latest 版本1.7.5 xray  最新的测试版本是1.8.3你可以升级为1.8.3看看 `Xray版本切换` 进行升级

**Comment by ShotoZhao** [comment]
> 打包是latest 版本1.7.5 xray 最新的测试版本是1.8.3你可以升级为1.8.3看看 `Xray版本切换` 进行升级

好吧，如果新版还是不行，是不是没办法了？哈哈哈

**Comment by qist** [comment]
你把那个日志也打开看看你代理的时候有日志过去没。看看能不能看到错误。

**Comment by ShotoZhao** [comment]
> "loglevel": "debug"
>     "access": "/var/log/xray-access.log",
>     "error": "/var/log/xray-error.log",

升级到1.8.3之后，错误日志
2023/07/02 10:53:17 [Debug] [3364528109] proxy/dokodemo: processing connection from: 127.0.0.1:58378
2023/07/02 10:53:17 [Info] [3364528109] proxy/dokodemo: received request for 127.0.0.1:58378
2023/07/02 10:53:17 [Info] [3364528109] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2023/07/02 10:53:22 [Debug] [257835235] proxy/dokodemo: processing connection from: 127.0.0.1:58380
2023/07/02 10:53:22 [Info] [257835235] proxy/dokodemo: received request for 127.0.0.1:58380
2023/07/02 10:53:22 [Info] [257835235] app/dispatcher: taking detour [api] for [tcp:127.0.0.1:0]
2023/07/02 10:53:22 [Info] [257835235] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport request > read tcp 127.0.0.1:62789->127.0.0.1:58380: read: connection reset by peer

**Comment by ShotoZhao** [comment]
> 你把那个日志也打开看看你代理的时候有日志过去没。看看能不能看到错误。

**Comment by qist** [comment]
看了一下http 代理日志
![image](https://github.com/qist/xray-ui/assets/7844620/e511ee28-bb27-4e76-ad14-dd7efc5bf033)
这个是xray 上游bug把。你可以xray 配置一个出口走代理。

**Comment by ShotoZhao** [comment]
> 看了一下http 代理日志 ![image](https://user-images.githubusercontent.com/7844620/250419782-e511ee28-bb27-4e76-ad14-dd7efc5bf033.png) 这个是xray 上游bug把。你可以xray 配置一个出口走代理。你可与到xray 项目提交bugs 或者就使用socks做代理了。

如果是xray的问题，大佬能看下是哪里的问题么？那边提了bug没人管-。-

**Comment by qist** [comment]
![image](https://github.com/qist/xray-ui/assets/7844620/0dcf1d2c-ab9c-423a-8a86-79b22359c929)
把这个关闭然后再测试看看

**Comment by ShotoZhao** [comment]
> ![image](https://user-images.githubusercontent.com/7844620/250422873-f24f80c5-ccf9-45cc-b01e-9b90fb62774d.png) 改成下面这样 ![image](https://user-images.githubusercontent.com/7844620/250422308-0dcf1d2c-ab9c-423a-8a86-79b22359c929.png) 再测试看看

佬，这样可以了，感谢！！！能解释下 大概原因麻？

**Comment by qist** [comment]
https://xtls.github.io/config/inbound.html#sniffingobject
解释把。

**Comment by ShotoZhao** [comment]
> https://xtls.github.io/config/inbound.html#sniffingobject 解释把。

佬，真滴牛，感谢啦！！开打赏功能的话，打点赏-.-
