### ISSUE TITLE
1.8.1升级后sockopt在入站编辑里刷不出来

### ISSUE THREAD

**Issue by GreatMichaelLee** [qist/xray-ui#9]
不知道怎么回事，两个vps都是装的1.8.1,都是reality,一个有，一个没有，sockopt部分 ctrl F5也没用

**Comment by qist** [comment]
我还原了

**Comment by GreatMichaelLee** [comment]
> 我还原了

好的，sockopt我刚看了下文档，貌似设置bbr有点用
